name: edtf
description: A library for parsing dates using the EDTF standard.
version: 1.0.0
homepage: https://github.com/maalexy/edtf
author: Alexy Marcell <alexy.marcel@hotmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.0.0
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
